/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test2 */

#ifndef _Included_Test2
#define _Included_Test2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test2
 * Method:    heapbufferoverflow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Test2_heapbufferoverflow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
