name: darwin-i386

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
jobs:
  darwin-i386-latest:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Brew packages
        # Initial unlik due to https://github.com/pypa/pipenv/issues/3831
        run: |
          brew update
          rm '/usr/local/bin/2to3'
          rm '/usr/local/bin/2to3-3.12'
          rm '/usr/local/bin/idle3'
          rm '/usr/local/bin/idle3.12'
          rm '/usr/local/bin/pydoc3'
          rm '/usr/local/bin/pydoc3.12'
          rm '/usr/local/bin/python3'
          rm '/usr/local/bin/python3-config'
          rm '/usr/local/bin/python3.12'
          rm '/usr/local/bin/python3.12-config'
          rm '/usr/local/share/man/man1/python3.1'
          rm '/usr/local/lib/pkgconfig/python3-embed.pc'
          rm '/usr/local/lib/pkgconfig/python3.pc'
          rm '/usr/local/Frameworks/Python.framework/Headers'
          rm '/usr/local/Frameworks/Python.framework/Python'
          rm '/usr/local/Frameworks/Python.framework/Resources'
          rm '/usr/local/Frameworks/Python.framework/Versions/Current'
          brew install gdb curl python llvm \
              openjdk ca-certificates gnupg
          pip3 install atheris
          brew update && brew install nodejs
      - name: Build
        run: cargo build --all-features --verbose
      - name: NPM packages
        run: |
          sudo npm install -g jsfuzz
          sudo npm install --save-dev @jazzer.js/core
      - name: Rust packages
        run: |
          curl https://sh.rustup.rs -o rustup.sh && chmod +x rustup.sh && \
          ./rustup.sh -y && rm rustup.sh
          rustup install nightly
          export PATH=/root/.cargo/bin:$PATH
          cargo install cargo-fuzz
      - name: Run tests
        run: |
          cargo test --release --verbose --lib -- --test-threads 1
          cargo test --release --verbose --package casr
